USE db_atividade_view;

SELECT *
FROM ALUNO;

SELECT *
FROM CURSO;

SELECT *
FROM DISCIPLINA;

SELECT *
FROM MATRICULA;

SELECT *
FROM PROFESSOR;

SELECT *
FROM TURMA;

-- 1
CREATE VIEW ALUNOS_COMPL AS
SELECT DISTINCT	ALUNO.NOME				AS ALUNO,
		DISCIPLINA.NOME			AS DISCIPLINA,
        CURSO.NOME				AS CURSO
FROM MATRICULA
INNER JOIN ALUNO ON
		ALUNO.ID_ALUNO = MATRICULA.ID_ALUNO
INNER JOIN DISCIPLINA ON
		DISCIPLINA.ID_DISCIPLINA = MATRICULA.ID_DISCIPLINA
INNER JOIN CURSO ON
		CURSO.ID_CURSO = DISCIPLINA.ID_CURSO
;
-- 2
CREATE VIEW TOTAL_ALUNOS AS
SELECT 	DISCIPLINA.NOME			AS DISCIPLINA,
		COUNT(ALUNO.ID_ALUNO) AS TOTAL_ALUNOS
FROM MATRICULA
INNER JOIN ALUNO ON
		ALUNO.ID_ALUNO = MATRICULA.ID_ALUNO
INNER JOIN DISCIPLINA ON
		DISCIPLINA.ID_DISCIPLINA = MATRICULA.ID_DISCIPLINA
GROUP BY DISCIPLINA.NOME
;
-- 3
CREATE VIEW STATUS_DISCIPLINAS AS
SELECT	ALUNO.NOME				AS ALUNO,
		DISCIPLINA.NOME			AS DISCIPLINA,
        MATRICULA.STATUS
FROM MATRICULA
INNER JOIN ALUNO ON
		ALUNO.ID_ALUNO = MATRICULA.ID_ALUNO
INNER JOIN DISCIPLINA ON
		DISCIPLINA.ID_DISCIPLINA = MATRICULA.ID_DISCIPLINA
INNER JOIN CURSO ON
		CURSO.ID_CURSO = DISCIPLINA.ID_CURSO
;
-- 4
CREATE VIEW PROFESSOR_COMPL AS
SELECT	PROFESSOR.NOME			AS PROFESSOR,
		DISCIPLINA.NOME			AS DISCIPLINA,
        TURMA.HORARIO
FROM TURMA
INNER JOIN PROFESSOR ON
		PROFESSOR.ID_PROFESSOR = TURMA.ID_PROFESSOR
INNER JOIN DISCIPLINA ON
		DISCIPLINA.ID_DISCIPLINA = TURMA.ID_DISCIPLINA
;
-- 5

SELECT	NOME,
		DATA_NASCIMENTO
FROM ALUNO
WHERE (DATEDIFF(CURDATE(), DATA_NASCIMENTO) /365) > 20
;
-- 6
CREATE VIEW CURSO_COMPL AS
SELECT	CURSO.NOME				AS CURSO,
		COUNT(DISCIPLINA.ID_DISCIPLINA) AS TOTAL_DISC,
        CURSO.CARGA_HORARIA
FROM CURSO
INNER JOIN DISCIPLINA ON
		DISCIPLINA.ID_CURSO = CURSO.ID_CURSO
GROUP BY	CURSO.NOME,
			CURSO.CARGA_HORARIA
;
-- 7
CREATE VIEW PROFESSOR_ESP AS
SELECT	NOME,
		ESPECIALIDADE
FROM PROFESSOR
;
-- 8
CREATE VIEW ALUNOS_MULTIDISCIPLINA AS
SELECT	ALUNO.NOME
FROM MATRICULA
INNER JOIN ALUNO ON
		ALUNO.ID_ALUNO = MATRICULA.ID_ALUNO
GROUP BY	ALUNO.NOME
HAVING	COUNT(MATRICULA.ID_DISCIPLINA) > 1
;
-- 9
CREATE VIEW CONCLUIDOS AS
SELECT	ALUNO.NOME,
		COUNT(MATRICULA.STATUS)
FROM MATRICULA
INNER JOIN ALUNO ON
		ALUNO.ID_ALUNO = MATRICULA.ID_ALUNO
WHERE	MATRICULA.STATUS LIKE ("C%")
GROUP BY	ALUNO.NOME
;
-- 10
CREATE VIEW TURMAS_SEMESTRE AS
SELECT	ID_TURMA
FROM TURMA
WHERE SEMESTRE LIKE '2024.1'
;
